# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BinaryIMGclassification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://binaryimgclassification.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e7a66a70247c448dafa48c6b71c9efc7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f279d0bf74542ebb2df2b1124513823 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: binaryimgclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7a66a70247c448dafa48c6b71c9efc7 }}/binaryimgclassification:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BinaryIMGclassification'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10e6fbe6e7254df9aebf7b0733f76ecd }}
        images: 'binaryimgclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7a66a70247c448dafa48c6b71c9efc7 }}/binaryimgclassification:${{ github.sha }}'